WIDTH=1440
HEIGHT=720

#easy/practice settings
COLUMNS_PRACTICE=10
ROWS_PRACTICE=10
MINES_PRACTICE=10

# course's suggestion:
# MINES_COUNT = (GRID_ZISE ** 2) / 4

CELL_COUNT = COLUMNS_PRACTICE * ROWS_PRACTICE


COLUMNS_EXPERT=30
ROWS_EXPERT=16
MINES_EXPERT = 99